<?php

ini_set('default_charset', "utf-8");

$listMots = [
	// Intro
	[
		"Je dirais que",
		"En général,",
		"Dans de nombreux domaines,",
		"Dans ce cas précis,",
		"Après analyse,",
		"En conclusion,",
		"Dans la plupart des cas,",
		"Objectivement,",
		"Vous n'ignorez pas que",
		"Effectivement,",
		"Nous savons tous que",
		"Quelque part,",
		"Typiquement,",
		"C'est par le dialogue que",
		"Désormais,",
		"Au jour d'aujourd'hui,",
		"Dans le contexte actuel,",
		"Au niveau du vécu,",
		"C'est dans l'adversité que",
		"C'est incontournable :",
		"A condition de s'adapter,",
		"Face à un environnement aussi mouvant,",
		"Tôt ou tard,",
		"En termes de déficits humains,",
		"Dans un certain nombre de cas,",
	],
	// Sujet
	[
		"l'autonomie",
		"l'excellence",
		"l'intervention",
		"l'objectif",
		"le diagnostic",
		"l'expérimentation",
		"la formation",
		"l'évaluation",
		"la finalité",
		"l'expression",
		"le management",
		"la méthode",
		"le vécu",
		"le recadrage",
		"la redondance",
		"la frontière",
		"l'application",
		"la compréhension",
		"l'efficacité",
		"la communication",
		"le défi",
		"l'adéquation",
		"la réflexion",
		"le brainstorming",
		"la logistique",
		"la pérennité",
		"l'effet de levier",
		"le challenge",
		"l'opérationnalisation",
		"la métamodèlisation",
		"le parallélisme",
		"la socio-dynamique",
		"l'intégration",
		"la planification",
		"la complexité",
		"la sensorialité",
		"le stress",
		"le partenariat",
		"le consensus",
		"l'amélioration",
		"l'effort soutenu",
		"l'avenir",
		"l'anticipation",
		"la globalisation",
		"la formalisation",
		"l'évolution",
		"le déploiement",
		"le levier de différentiation",
		"la richesse du réseau",
	],
	// Verbe
	[
		"impacte",
		"renforce",
		"mobilise",
		"revèle",
		"stimule",
		"modifie",
		"clarifie",
		"renouvelle",
		"identifie",
		"perfectionne",
		"développe",
		"dynamise",
		"programme",
		"ponctue",
		"améliore",
		"implique",
		"conditionne",
		"transcende",
		"doit éclaircir",
		"peut faire rapidement progresser",
		"consolide",
		"doit pouvoir décliner",
		"peut vraisemblablement s'harmoniser avec",
		"galvanise",
		"métabolise",
		"s'inscrit dans",
	],
	// COD
	[
		"les paradigmes",
		"les facteurs",
		"les processus",
		"les paramètres",
		"les changements",
		"les concepts",
		"les savoir-faire",
		"les problèmes",
		"les indicateurs",
		"les résultats",
		"les effets",
		"les blocages",
		"les besoins",
		"les paradoxes",
		"les niveaux",
		"les thèmes",
		"les inputs",
		"les équilibres",
		"les acquis",
		"les impacts",
	],
	// Adjectif
	[
		"cyndinogenes",
		"institutionnels",
		"organisationnels",
		"qualitatifs",
		"analytiques",
		"caractéristiques",
		"motivationnels",
		"pédagogiques",
		"répresentatifs",
		"participatifs",
		"cumulatifs",
		"stratégiques",
		"neuro-linguistiques",
		"systémiques",
		"adjacents",
		"hiérarchiques",
		"informatiques",
		"tertiaires",
		"inter-culturels",
		"ad-hoc",
		"transfonctionnels",
		"globalo-superficiels",
		"exogènes",
		"transversaux",
		"corrélatifs",
		"synthétiques",
		"hypothético-déductifs",
		"critiques",
		"transactionnels",
		"réductionnistes",
		"majeurs",
		"discriminants",
		"cognitifs",
		"discriminants",
		"sociétaux",
	],
	// Complément
	[
		": on va droit dans le mur",
		"de la performance",
		"du dispositif",
		"de l'entreprise",
		"du groupe",
		"du projet",
		"des bénéficiaires",
		"de la hiérarchie",
		"des pratiques",
		"de la démarche",
		"des acteurs",
		"de la problématique",
		"des structures",
		"du méta-contexte",
		"de la non-qualité",
		"du rattachement",
		"des synergies",
		"de l'individu",
		"des supports",
		"du plan d'action",
		"des axes de progrès",
		"dans le bon sens",
		"des ressources",
		"de notre compétence",
		"du potentiel",
		"du développement",
		"des leaders",
		"de l'équipe",
		"des imbrications",
		"des neuro-sciences",
		"de troisième generation",
		"à tous les niveaux",
		"de chacun",
		"des difficultés",
		"du professionnalisme",
		"en permanence",
		"de la technologie",
		"de l'investissement",
		"de la communauté logicielle",
		"avec l'ensemble des acteurs",
		"du référentiel",
		"du schéma directeur",
	],
];

function random_value($array){
	$values=array_values($array);
	return $values[mt_rand(0, count($values) - 1)];
}

$listPhrases = [];
for ($i=0; $i<10; $i++) {
	$intro 	= random_value($listMots[0]);
	$sujet 	= random_value($listMots[1]);
	$verbe 	= random_value($listMots[2]);
	$cod 	= random_value($listMots[3]);
	$adj 	= random_value($listMots[4]);
	$compl 	= random_value($listMots[5]);
	$listPhrases[] = $intro.' <b>'.$sujet.'</b> '.$verbe.' <b>'.$cod.'</b> '.$adj.' '.$compl.'.';
}
